// Generated by gencpp from file limo_motion_controller/OverrideMotionResponse.msg
// DO NOT EDIT!


#ifndef LIMO_MOTION_CONTROLLER_MESSAGE_OVERRIDEMOTIONRESPONSE_H
#define LIMO_MOTION_CONTROLLER_MESSAGE_OVERRIDEMOTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace limo_motion_controller
{
template <class ContainerAllocator>
struct OverrideMotionResponse_
{
  typedef OverrideMotionResponse_<ContainerAllocator> Type;

  OverrideMotionResponse_()
    : alreadyRunning(false)  {
    }
  OverrideMotionResponse_(const ContainerAllocator& _alloc)
    : alreadyRunning(false)  {
  (void)_alloc;
    }



   typedef uint8_t _alreadyRunning_type;
  _alreadyRunning_type alreadyRunning;





  typedef boost::shared_ptr< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OverrideMotionResponse_

typedef ::limo_motion_controller::OverrideMotionResponse_<std::allocator<void> > OverrideMotionResponse;

typedef boost::shared_ptr< ::limo_motion_controller::OverrideMotionResponse > OverrideMotionResponsePtr;
typedef boost::shared_ptr< ::limo_motion_controller::OverrideMotionResponse const> OverrideMotionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator1> & lhs, const ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.alreadyRunning == rhs.alreadyRunning;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator1> & lhs, const ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limo_motion_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "874749314d3cdd5b8d70590d992e9aad";
  }

  static const char* value(const ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x874749314d3cdd5bULL;
  static const uint64_t static_value2 = 0x8d70590d992e9aadULL;
};

template<class ContainerAllocator>
struct DataType< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limo_motion_controller/OverrideMotionResponse";
  }

  static const char* value(const ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool alreadyRunning\n"
;
  }

  static const char* value(const ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.alreadyRunning);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OverrideMotionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limo_motion_controller::OverrideMotionResponse_<ContainerAllocator>& v)
  {
    s << indent << "alreadyRunning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alreadyRunning);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMO_MOTION_CONTROLLER_MESSAGE_OVERRIDEMOTIONRESPONSE_H
