version: '3'
services:
  terminal:
    container_name: terminal
    image: thesis
    network_mode: host
    volumes:
      - "./:/home/thesis:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true

  rviz:
    container_name: rviz
    image: thesis
    runtime: nvidia
    network_mode: host
    command: zsh -c 'source ~/.zshrc && rviz -d /home/thesis/ROS/src/ugv_sim/limo/limo_description/rviz/model_display.rviz'
    volumes:
      - "./:/home/thesis:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    restart: always
    stdin_open: true
    privileged: true

  gazebo:
    depends_on:
      - rviz
    container_name: gazebo
    image: thesis
    runtime: nvidia
    network_mode: host
    command: zsh -c 'source ~/.zshrc && cd /home/thesis/ROS && catkin build && roslaunch limo_gazebo_sim limo_ackerman.launch'
    volumes:
      - "./:/home/thesis:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    privileged: true
    stdin_open: true
  roscore:
    container_name: roscore
    image: thesis
    network_mode: "host"
    restart: always
    command: zsh -c 'source ~/.zshrc && roscore'
    volumes:
      - "./:/home/thesis:rw"
    tty: true
    privileged: true
  
  terminallimo:
    container_name: terminallimo
    image: thesislimo
    network_mode: host
    volumes:
      - "./:/home/thesis:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true


  roscorelimo:
    container_name: roscorelimo
    image: thesislimo
    network_mode: "host"
    restart: always
    command: zsh -c 'source ~/.zshrc && roscore'
    volumes:
      - "./:/home/thesis:rw"
    tty: true
    privileged: true

  rvizlimo:
    container_name: rviz
    image: thesislimo
    runtime: nvidia
    network_mode: host
    command: zsh -c 'source ~/.zshrc && rviz'
    volumes:
      - "./:/home/thesis:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    restart: always
    stdin_open: true
    privileged: true