// Generated by gencpp from file limo_yolo/map.msg
// DO NOT EDIT!


#ifndef LIMO_YOLO_MESSAGE_MAP_H
#define LIMO_YOLO_MESSAGE_MAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>
#include <geometry_msgs/PointStamped.h>

namespace limo_yolo
{
template <class ContainerAllocator>
struct map_
{
  typedef map_<ContainerAllocator> Type;

  map_()
    : obstacles()
    , goal()  {
    }
  map_(const ContainerAllocator& _alloc)
    : obstacles(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PointStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PointStamped_<ContainerAllocator> >> _obstacles_type;
  _obstacles_type obstacles;

   typedef std::vector< ::geometry_msgs::PointStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PointStamped_<ContainerAllocator> >> _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::limo_yolo::map_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limo_yolo::map_<ContainerAllocator> const> ConstPtr;

}; // struct map_

typedef ::limo_yolo::map_<std::allocator<void> > map;

typedef boost::shared_ptr< ::limo_yolo::map > mapPtr;
typedef boost::shared_ptr< ::limo_yolo::map const> mapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limo_yolo::map_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limo_yolo::map_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limo_yolo::map_<ContainerAllocator1> & lhs, const ::limo_yolo::map_<ContainerAllocator2> & rhs)
{
  return lhs.obstacles == rhs.obstacles &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limo_yolo::map_<ContainerAllocator1> & lhs, const ::limo_yolo::map_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limo_yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::limo_yolo::map_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limo_yolo::map_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limo_yolo::map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limo_yolo::map_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limo_yolo::map_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limo_yolo::map_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limo_yolo::map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e1faeb293b7b99053a7f0deeb8a2c78";
  }

  static const char* value(const ::limo_yolo::map_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e1faeb293b7b990ULL;
  static const uint64_t static_value2 = 0x53a7f0deeb8a2c78ULL;
};

template<class ContainerAllocator>
struct DataType< ::limo_yolo::map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limo_yolo/map";
  }

  static const char* value(const ::limo_yolo::map_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limo_yolo::map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PointStamped[] obstacles\n"
"geometry_msgs/PointStamped[] goal\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::limo_yolo::map_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limo_yolo::map_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacles);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct map_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limo_yolo::map_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limo_yolo::map_<ContainerAllocator>& v)
  {
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.goal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMO_YOLO_MESSAGE_MAP_H
