# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from limo_motion_controller/MotionPlan.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import limo_motion_controller.msg

class MotionPlan(genpy.Message):
  _md5sum = "862f364494b8552b6422445d2907f57e"
  _type = "limo_motion_controller/MotionPlan"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """limo_motion_controller/MovementController[] sequence
================================================================================
MSG: limo_motion_controller/MovementController
float32 speed
float32 angle
float32 duration"""
  __slots__ = ['sequence']
  _slot_types = ['limo_motion_controller/MovementController[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sequence

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotionPlan, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sequence is None:
        self.sequence = []
    else:
      self.sequence = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.sequence)
      buff.write(_struct_I.pack(length))
      for val1 in self.sequence:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.speed, _x.angle, _x.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sequence is None:
        self.sequence = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sequence = []
      for i in range(0, length):
        val1 = limo_motion_controller.msg.MovementController()
        _x = val1
        start = end
        end += 12
        (_x.speed, _x.angle, _x.duration,) = _get_struct_3f().unpack(str[start:end])
        self.sequence.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.sequence)
      buff.write(_struct_I.pack(length))
      for val1 in self.sequence:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.speed, _x.angle, _x.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sequence is None:
        self.sequence = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sequence = []
      for i in range(0, length):
        val1 = limo_motion_controller.msg.MovementController()
        _x = val1
        start = end
        end += 12
        (_x.speed, _x.angle, _x.duration,) = _get_struct_3f().unpack(str[start:end])
        self.sequence.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
