// Generated by gencpp from file limo_behaviour_tree/EndGoal.msg
// DO NOT EDIT!


#ifndef LIMO_BEHAVIOUR_TREE_MESSAGE_ENDGOAL_H
#define LIMO_BEHAVIOUR_TREE_MESSAGE_ENDGOAL_H

#include <ros/service_traits.h>


#include <limo_behaviour_tree/EndGoalRequest.h>
#include <limo_behaviour_tree/EndGoalResponse.h>


namespace limo_behaviour_tree
{

struct EndGoal
{

typedef EndGoalRequest Request;
typedef EndGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EndGoal
} // namespace limo_behaviour_tree


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::limo_behaviour_tree::EndGoal > {
  static const char* value()
  {
    return "f43f04c866179f13e0ff9145477de5ab";
  }

  static const char* value(const ::limo_behaviour_tree::EndGoal&) { return value(); }
};

template<>
struct DataType< ::limo_behaviour_tree::EndGoal > {
  static const char* value()
  {
    return "limo_behaviour_tree/EndGoal";
  }

  static const char* value(const ::limo_behaviour_tree::EndGoal&) { return value(); }
};


// service_traits::MD5Sum< ::limo_behaviour_tree::EndGoalRequest> should match
// service_traits::MD5Sum< ::limo_behaviour_tree::EndGoal >
template<>
struct MD5Sum< ::limo_behaviour_tree::EndGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::limo_behaviour_tree::EndGoal >::value();
  }
  static const char* value(const ::limo_behaviour_tree::EndGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::limo_behaviour_tree::EndGoalRequest> should match
// service_traits::DataType< ::limo_behaviour_tree::EndGoal >
template<>
struct DataType< ::limo_behaviour_tree::EndGoalRequest>
{
  static const char* value()
  {
    return DataType< ::limo_behaviour_tree::EndGoal >::value();
  }
  static const char* value(const ::limo_behaviour_tree::EndGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::limo_behaviour_tree::EndGoalResponse> should match
// service_traits::MD5Sum< ::limo_behaviour_tree::EndGoal >
template<>
struct MD5Sum< ::limo_behaviour_tree::EndGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::limo_behaviour_tree::EndGoal >::value();
  }
  static const char* value(const ::limo_behaviour_tree::EndGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::limo_behaviour_tree::EndGoalResponse> should match
// service_traits::DataType< ::limo_behaviour_tree::EndGoal >
template<>
struct DataType< ::limo_behaviour_tree::EndGoalResponse>
{
  static const char* value()
  {
    return DataType< ::limo_behaviour_tree::EndGoal >::value();
  }
  static const char* value(const ::limo_behaviour_tree::EndGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIMO_BEHAVIOUR_TREE_MESSAGE_ENDGOAL_H
