// Generated by gencpp from file limo_behaviour_tree/PathType.msg
// DO NOT EDIT!


#ifndef LIMO_BEHAVIOUR_TREE_MESSAGE_PATHTYPE_H
#define LIMO_BEHAVIOUR_TREE_MESSAGE_PATHTYPE_H

#include <ros/service_traits.h>


#include <limo_behaviour_tree/PathTypeRequest.h>
#include <limo_behaviour_tree/PathTypeResponse.h>


namespace limo_behaviour_tree
{

struct PathType
{

typedef PathTypeRequest Request;
typedef PathTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathType
} // namespace limo_behaviour_tree


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::limo_behaviour_tree::PathType > {
  static const char* value()
  {
    return "11e5c53def65876fc1708cc2295e05a4";
  }

  static const char* value(const ::limo_behaviour_tree::PathType&) { return value(); }
};

template<>
struct DataType< ::limo_behaviour_tree::PathType > {
  static const char* value()
  {
    return "limo_behaviour_tree/PathType";
  }

  static const char* value(const ::limo_behaviour_tree::PathType&) { return value(); }
};


// service_traits::MD5Sum< ::limo_behaviour_tree::PathTypeRequest> should match
// service_traits::MD5Sum< ::limo_behaviour_tree::PathType >
template<>
struct MD5Sum< ::limo_behaviour_tree::PathTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::limo_behaviour_tree::PathType >::value();
  }
  static const char* value(const ::limo_behaviour_tree::PathTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::limo_behaviour_tree::PathTypeRequest> should match
// service_traits::DataType< ::limo_behaviour_tree::PathType >
template<>
struct DataType< ::limo_behaviour_tree::PathTypeRequest>
{
  static const char* value()
  {
    return DataType< ::limo_behaviour_tree::PathType >::value();
  }
  static const char* value(const ::limo_behaviour_tree::PathTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::limo_behaviour_tree::PathTypeResponse> should match
// service_traits::MD5Sum< ::limo_behaviour_tree::PathType >
template<>
struct MD5Sum< ::limo_behaviour_tree::PathTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::limo_behaviour_tree::PathType >::value();
  }
  static const char* value(const ::limo_behaviour_tree::PathTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::limo_behaviour_tree::PathTypeResponse> should match
// service_traits::DataType< ::limo_behaviour_tree::PathType >
template<>
struct DataType< ::limo_behaviour_tree::PathTypeResponse>
{
  static const char* value()
  {
    return DataType< ::limo_behaviour_tree::PathType >::value();
  }
  static const char* value(const ::limo_behaviour_tree::PathTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIMO_BEHAVIOUR_TREE_MESSAGE_PATHTYPE_H
