// Generated by gencpp from file limo_behaviour_tree/PathTypeRequest.msg
// DO NOT EDIT!


#ifndef LIMO_BEHAVIOUR_TREE_MESSAGE_PATHTYPEREQUEST_H
#define LIMO_BEHAVIOUR_TREE_MESSAGE_PATHTYPEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace limo_behaviour_tree
{
template <class ContainerAllocator>
struct PathTypeRequest_
{
  typedef PathTypeRequest_<ContainerAllocator> Type;

  PathTypeRequest_()
    : pathType(0)  {
    }
  PathTypeRequest_(const ContainerAllocator& _alloc)
    : pathType(0)  {
  (void)_alloc;
    }



   typedef int32_t _pathType_type;
  _pathType_type pathType;





  typedef boost::shared_ptr< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PathTypeRequest_

typedef ::limo_behaviour_tree::PathTypeRequest_<std::allocator<void> > PathTypeRequest;

typedef boost::shared_ptr< ::limo_behaviour_tree::PathTypeRequest > PathTypeRequestPtr;
typedef boost::shared_ptr< ::limo_behaviour_tree::PathTypeRequest const> PathTypeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator1> & lhs, const ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pathType == rhs.pathType;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator1> & lhs, const ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limo_behaviour_tree

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11e5c53def65876fc1708cc2295e05a4";
  }

  static const char* value(const ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11e5c53def65876fULL;
  static const uint64_t static_value2 = 0xc1708cc2295e05a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limo_behaviour_tree/PathTypeRequest";
  }

  static const char* value(const ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 pathType\n"
;
  }

  static const char* value(const ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pathType);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathTypeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limo_behaviour_tree::PathTypeRequest_<ContainerAllocator>& v)
  {
    s << indent << "pathType: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pathType);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMO_BEHAVIOUR_TREE_MESSAGE_PATHTYPEREQUEST_H
