// Generated by gencpp from file limo_behaviour_tree/TypeObjectTrackingRequest.msg
// DO NOT EDIT!


#ifndef LIMO_BEHAVIOUR_TREE_MESSAGE_TYPEOBJECTTRACKINGREQUEST_H
#define LIMO_BEHAVIOUR_TREE_MESSAGE_TYPEOBJECTTRACKINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace limo_behaviour_tree
{
template <class ContainerAllocator>
struct TypeObjectTrackingRequest_
{
  typedef TypeObjectTrackingRequest_<ContainerAllocator> Type;

  TypeObjectTrackingRequest_()
    : objectID(0)  {
    }
  TypeObjectTrackingRequest_(const ContainerAllocator& _alloc)
    : objectID(0)  {
  (void)_alloc;
    }



   typedef int32_t _objectID_type;
  _objectID_type objectID;





  typedef boost::shared_ptr< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TypeObjectTrackingRequest_

typedef ::limo_behaviour_tree::TypeObjectTrackingRequest_<std::allocator<void> > TypeObjectTrackingRequest;

typedef boost::shared_ptr< ::limo_behaviour_tree::TypeObjectTrackingRequest > TypeObjectTrackingRequestPtr;
typedef boost::shared_ptr< ::limo_behaviour_tree::TypeObjectTrackingRequest const> TypeObjectTrackingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator1> & lhs, const ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.objectID == rhs.objectID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator1> & lhs, const ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limo_behaviour_tree

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b08c3191adc4004289244e57c20d2f6";
  }

  static const char* value(const ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b08c3191adc4004ULL;
  static const uint64_t static_value2 = 0x289244e57c20d2f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limo_behaviour_tree/TypeObjectTrackingRequest";
  }

  static const char* value(const ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 objectID\n"
;
  }

  static const char* value(const ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objectID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TypeObjectTrackingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limo_behaviour_tree::TypeObjectTrackingRequest_<ContainerAllocator>& v)
  {
    s << indent << "objectID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.objectID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMO_BEHAVIOUR_TREE_MESSAGE_TYPEOBJECTTRACKINGREQUEST_H
