// Generated by gencpp from file limo_behaviour_tree/TypeObjectTrackingResponse.msg
// DO NOT EDIT!


#ifndef LIMO_BEHAVIOUR_TREE_MESSAGE_TYPEOBJECTTRACKINGRESPONSE_H
#define LIMO_BEHAVIOUR_TREE_MESSAGE_TYPEOBJECTTRACKINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace limo_behaviour_tree
{
template <class ContainerAllocator>
struct TypeObjectTrackingResponse_
{
  typedef TypeObjectTrackingResponse_<ContainerAllocator> Type;

  TypeObjectTrackingResponse_()
    {
    }
  TypeObjectTrackingResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TypeObjectTrackingResponse_

typedef ::limo_behaviour_tree::TypeObjectTrackingResponse_<std::allocator<void> > TypeObjectTrackingResponse;

typedef boost::shared_ptr< ::limo_behaviour_tree::TypeObjectTrackingResponse > TypeObjectTrackingResponsePtr;
typedef boost::shared_ptr< ::limo_behaviour_tree::TypeObjectTrackingResponse const> TypeObjectTrackingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace limo_behaviour_tree

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limo_behaviour_tree/TypeObjectTrackingResponse";
  }

  static const char* value(const ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TypeObjectTrackingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::limo_behaviour_tree::TypeObjectTrackingResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LIMO_BEHAVIOUR_TREE_MESSAGE_TYPEOBJECTTRACKINGRESPONSE_H
