// Generated by gencpp from file limo_behaviour_tree/TypeObjectTracking.msg
// DO NOT EDIT!


#ifndef LIMO_BEHAVIOUR_TREE_MESSAGE_TYPEOBJECTTRACKING_H
#define LIMO_BEHAVIOUR_TREE_MESSAGE_TYPEOBJECTTRACKING_H

#include <ros/service_traits.h>


#include <limo_behaviour_tree/TypeObjectTrackingRequest.h>
#include <limo_behaviour_tree/TypeObjectTrackingResponse.h>


namespace limo_behaviour_tree
{

struct TypeObjectTracking
{

typedef TypeObjectTrackingRequest Request;
typedef TypeObjectTrackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TypeObjectTracking
} // namespace limo_behaviour_tree


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::limo_behaviour_tree::TypeObjectTracking > {
  static const char* value()
  {
    return "0b08c3191adc4004289244e57c20d2f6";
  }

  static const char* value(const ::limo_behaviour_tree::TypeObjectTracking&) { return value(); }
};

template<>
struct DataType< ::limo_behaviour_tree::TypeObjectTracking > {
  static const char* value()
  {
    return "limo_behaviour_tree/TypeObjectTracking";
  }

  static const char* value(const ::limo_behaviour_tree::TypeObjectTracking&) { return value(); }
};


// service_traits::MD5Sum< ::limo_behaviour_tree::TypeObjectTrackingRequest> should match
// service_traits::MD5Sum< ::limo_behaviour_tree::TypeObjectTracking >
template<>
struct MD5Sum< ::limo_behaviour_tree::TypeObjectTrackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::limo_behaviour_tree::TypeObjectTracking >::value();
  }
  static const char* value(const ::limo_behaviour_tree::TypeObjectTrackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::limo_behaviour_tree::TypeObjectTrackingRequest> should match
// service_traits::DataType< ::limo_behaviour_tree::TypeObjectTracking >
template<>
struct DataType< ::limo_behaviour_tree::TypeObjectTrackingRequest>
{
  static const char* value()
  {
    return DataType< ::limo_behaviour_tree::TypeObjectTracking >::value();
  }
  static const char* value(const ::limo_behaviour_tree::TypeObjectTrackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::limo_behaviour_tree::TypeObjectTrackingResponse> should match
// service_traits::MD5Sum< ::limo_behaviour_tree::TypeObjectTracking >
template<>
struct MD5Sum< ::limo_behaviour_tree::TypeObjectTrackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::limo_behaviour_tree::TypeObjectTracking >::value();
  }
  static const char* value(const ::limo_behaviour_tree::TypeObjectTrackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::limo_behaviour_tree::TypeObjectTrackingResponse> should match
// service_traits::DataType< ::limo_behaviour_tree::TypeObjectTracking >
template<>
struct DataType< ::limo_behaviour_tree::TypeObjectTrackingResponse>
{
  static const char* value()
  {
    return DataType< ::limo_behaviour_tree::TypeObjectTracking >::value();
  }
  static const char* value(const ::limo_behaviour_tree::TypeObjectTrackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIMO_BEHAVIOUR_TREE_MESSAGE_TYPEOBJECTTRACKING_H
